apiVersion: authorization.openshift.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"cluster-admin-sa-argo-paas-gitops"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cluster-admin"},"subjects":[{"kind":"ServiceAccount","name":"argocd-argocd-application-controller","namespace":"paas-gitops"}]}
  creationTimestamp: "2023-03-31T07:07:05Z"
  name: cluster-admin-sa-argo-paas-gitops
  resourceVersion: "113051"
  uid: 3e913725-63e2-4526-8cb1-a350ad5f192e
roleRef:
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: paas-gitops
userNames:
- system:serviceaccount:paas-gitops:argocd-argocd-application-controller
